### ISSUE TITLE
production deploy with pm2 and docker

### ISSUE THREAD

**Issue by stkac** [wemake-services/wemake-vue-template#729]
Hi @sobolevn I tried to recreate the pm2 stage and from a few commits ago but it's no possible for me...

I get many SyntaxError...

I ask: **is possible make a branch with this feature?** I use docker everywhere and your project is an swiss knife, I hope it's can be also used on production...

Thanks in advance,

**Comment by sobolevn** [comment]
Can you please share your config?

And also show an error which happens.

**Comment by stkac** [comment]
Hi, @sobolevn here the output and the code

```
[2018-08-20T12:11:58.852Z] PM2 log: Launching in no daemon mode
[2018-08-20T12:11:58.943Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Vue App id:0
[2018-08-20T12:11:59.018Z] PM2 log: App name:Vue App id:0 online
[2018-08-20T12:11:59.020Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Vue App id:1
[2018-08-20T12:11:59.023Z] PM2 error: (node:1) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
[2018-08-20T12:11:59.115Z] PM2 log: App name:Vue App id:1 online
[2018-08-20T12:11:59.117Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Vue App id:2
[2018-08-20T12:11:59.120Z] PM2 error: (node:1) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
[2018-08-20T12:11:59.229Z] PM2 log: App name:Vue App id:2 online
[2018-08-20T12:11:59.230Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Vue App id:3
[2018-08-20T12:11:59.232Z] PM2 error: (node:1) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
Error: Cannot find module '/code/dist/vue-ssr-bundle.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at createServer (/code/server/server.js:15:18)
    at Object.<anonymous> (/code/server/index.js:4:13)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```
here the code: **it's come form the commit: 90197466fa17b9fb02a0936da04f5b0b53d2d054**

https://github.com/stkac/nuxtemp

following the recommendation : https://wemake-services.gitbook.io/wemake-vue-template/production#docker

thanks in advance,

**Comment by sobolevn** [comment]
You are using `node8.8` when we are already using `node10`.

So, maybe upgrading `node` will fix it?
Or downgrading `stylelint-webpack-plugin` as a second guess.

**Comment by sobolevn** [comment]
Closing as stale. Please, reopen if you still have this problem.
